### ISSUE TITLE
Update project requirements

### ISSUE THREAD

**Issue by eutkan** [bounswe/bounswe2018group10#13]
We need to revise and update the project requirements according to the feedback we got from our customer.

**Comment by alimturkmen** [comment]
I went over all feedback except last 7, starting with _"The first requirement of 1.2.2 can be decomposed"_. Further help is required for the remaining items. Also I've highlighted two items to ask for a clarification.

**Comment by alimturkmen** [comment]
Enumeration should, I think, be left undone till the last review to prevent re-dos.
