### ISSUE TITLE
Add tag array to freelancer profile

### ISSUE THREAD

**Issue by barisesmer** [bounswe/bounswe2018group10#134]
### I'm submitting a ...

- [ ] bug report
- [x] feature request
- [ ] support request

### Expected behavior
Freelancer should have tags associated with them that shows their skills

### Actual behavior
Currently we don't have this feature implemented

### Additional Notes
This feature requires that we implement seperate freelancer/client profiles first.

**Comment by alimturkmen** [comment]
Done in #171
