### ISSUE TITLE
Handle the security risks reported by Github

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group10#150]
### The GitHub repo has identified some risks related to the older versions of libs being used. Need to update them to secure the app

- [ ] upgrade requests to version >=2.20.0
- [ ] upgrade flask to version >=0.12.3

**Comment by kilicbaran** [comment]
Updated the libraries in following commits: f0bdf16987b3929fdbe0f6ffb08e03076760a1fe, 62dd33228c54a14a3edfd78af95357f646ea1f59, 6ec61078abfd26eb3e3d6073d3208024489d16db
