### ISSUE TITLE
Database Field Improvements

### ISSUE THREAD

**Issue by meverg** [bounswe/bounswe2018group10#157]
Milestone:
+ seperate completed fields for roles
+ verified (for accepted project)

Freelancer Profile:
+ role tags

Project:
+ status

> more improvements can be done
### I'm submitting a ...

- [ ] bug report
- [X] feature request
- [ ] support request

**Comment by alimturkmen** [comment]
Tags are added both for freelancer and client profiles in #171.  I think, rest is not much necessary. Therefore, I am closing this issue for now.
