### ISSUE TITLE
User scenario mockup for customer

### ISSUE THREAD

**Issue by afcelimli** [bounswe/bounswe2018group10#32]
-You can select another person as partner for this task.

**Comment by meverg** [comment]
@afcelimli can you please mention for which user scenario I should prepare mockups?

**Comment by afcelimli** [comment]
For customer. You can find the related scenario in user scenarios document. The title is "Customer-Susan Kelso".

**Comment by meverg** [comment]
I added the [mockups](https://github.com/bounswe/bounswe2018group10/wiki/User-Scenarios#customer---susan-kelso)
