### ISSUE TITLE
Wiki page link

### ISSUE THREAD

**Issue by kaanozgen12** [bounswe/bounswe2018group10#33]
Wiki page should be available for access through readme page, too.

**Comment by bayneri** [comment]
There is a link actually, the HoneyBadgers logo at readme linked to wiki page

**Comment by kilicbaran** [comment]
We need an explicit link to wiki. We can't assume that everyone who sees the image will think that is is a link to the wiki page.

**Comment by bayneri** [comment]
Actually I don't think that is needed. There already are 13 ways to go wiki tab from repo's home page.
1st is the GitHub's own tabs at repo header,
2nd is the logo and the rest are links to users' wiki pages under the 'Team Members' at readme @kilicbaran

**Comment by abdusco** [comment]
Still, you can't rely on your own assumptions with the end user. Without hovering over the logo, it's not possible to notice that it's actually a link.
I think an obvious statement with a link, like "For further information, please see the [Wiki](/url/to/wiki)", would be more helpful.

**Comment by meverg** [comment]
done: [new readMe](https://github.com/bounswe/bounswe2018group10/blob/develop/README.md#rocket-freelancer--collaboration-platform) 
_credits for @abdusco_
