### ISSUE TITLE
Problems in Requirements Clustering

### ISSUE THREAD

**Issue by meverg** [bounswe/bounswe2018group10#36]
Separation of user/system requirements should be revised as referenced in the feedback:
"There are lots of cases about the complication about user/system requirements. If a user is able to do something within the system, it is a user requirement. If user is provided with a functionality without doing anything (such as the system shall recommend related stuff to the user, the user does not have to do anything to retrieve requirements), it is a system requirement. You need to revise the clustering of the requirements. 
What about the home page of the users, and browsing among the available projects?"

**Comment by alimturkmen** [comment]
Following items are moved to the user requirements part:

- 1.2.1.2 A user shall be able to filter search results down to their certain categories, tags, and budget range.
- 1.2.1.5 A user shall be able to save and rerun a search query and shall be given an option to be notified of any new postings that correspond to said search.
- 1.2.2.1 During post creation, a user shall be able to add/remove tags from a searchable list, which includes a list of tag recommendation based on the project title.
- 1.2.3.4 A client shall be able to contract any freelancer who placed a bid on the project.
- 1.2.2.2 A user shall be able to pick a relevant budget range for the project from a certain list of options.

If there is a mistake, please inform me.
