### ISSUE TITLE
Search as a user requirement

### ISSUE THREAD

**Issue by sbasrik** [bounswe/bounswe2018group10#39]
### I'm submitting a ...

- [ ] bug report
- [x] feature request
- [ ] support request

### Expected behavior
Search should be in user requirements.

### Actual behavior
Search is not in user requirements.

**Comment by bayneri** [comment]
can you clarify the request @sbasrik

**Comment by sbasrik** [comment]
Sorry, it should be in "user" requirements, not in "system" requirements.
