### ISSUE TITLE
PR and issue templates are missing

### ISSUE THREAD

**Issue by abdusco** [bounswe/bounswe2018group10#4]
A template for pull requests and issues will help ensure all topics follow a certain outline and simplify analyzing and filtering requests.

For more info:  
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by barisesmer** [comment]
A sample issue template is added.

**Comment by bayneri** [comment]
i've added the pr template to [contribution guideline](https://github.com/bounswe/bounswe2018group10/wiki/Contribution-Guideline)
