### ISSUE TITLE
Twitter sentiment app should support mobile browsers

### ISSUE THREAD

**Issue by bayneri** [bounswe/bounswe2018group10#64]
when I view it on a mobile browsers it does not respect the viewport size and rendered page looks tiny

**Comment by abdusco** [comment]
I agree, that bothered me too.  
I'll push a quick fix then accept the PR.

**Comment by abdusco** [comment]
Fixed with https://github.com/bounswe/bounswe2018group10/commit/e419a422c4117f6f27d5fa9135e76514708510e1
