### ISSUE TITLE
Requirements analysis

### ISSUE THREAD

**Issue by alimturkmen** [bounswe/bounswe2018group10#8]
The requirements of the project should be analyzed and reported.

**Comment by abdusco** [comment]
Working on merging the updates and revisions. Will add a page to Wiki once I'm finished.

**Comment by barisesmer** [comment]
I just added a draft of the requirements, should be easy to complete now.

**Comment by abdusco** [comment]
Thank you @barisesmer, I've completed an initial draft of the requirements and added to Wiki.
