### ISSUE TITLE
Readme for SentimentAnalysis

### ISSUE THREAD

**Issue by bayneri** [bounswe/bounswe2018group10#83]
- [ ] bug report
- [x] feature request
- [ ] support request

Related to #78 

### Expected behavior
A brief explanation of the app as a readme file

### Actual behavior
Lots of code which is good but on the other hand doesn't mean anything at first sight

**Comment by kilicbaran** [comment]
This project is not mine. It is Ahmet Faruk Çelimli's project.

**Comment by afcelimli** [comment]
Done.
