### ISSUE TITLE
Search Job Twitter App is not reachable

### ISSUE THREAD

**Issue by abdusco** [bounswe/bounswe2018group10#85]
I cannot reach the application using [the link in Wiki](http://search-job-env.sfhu8nxszy.us-west-2.elasticbeanstalk.com/). It's sending an empty 502 response.  
Has a new version been deployed without testing if it works? I'm not sure on whose AWS account it's hosted, but checking the container status and logs on AWS might help.

### I'm submitting a ...

- [x] bug report
- [ ] support request
- [ ] feature request

**Comment by kilicbaran** [comment]
My AWS free tier period expired. Not to be charged, I removed the deployment.

**Comment by abdusco** [comment]
Yeah, I'm having the same issue. Turns out hosting is free but reserving an IP is not. I've been charged $2 so far for using an Elastic IP.  
Heroku is free, though, feel free to host the application there.

**Comment by kilicbaran** [comment]
Thanks for suggesting Heroku. I deployed my project on it. The new link is on [wiki](https://github.com/bounswe/bounswe2018group10/wiki#twitter-api-project-links)
